title: Michał Dams # your name (or website title) here
logo: "/images/profilowe.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  <br>AI student during last semester of Master's degree studies. Experienced in working as a programmer for international corporation as well as small-scale company. Seeking to expand programming skills. Involved, communicative, well-organized, responsible, effective in achieving
goals.<br>
  Second description 
#   <br><br>
  <a href="https://www.linkedin.com/in/micha%C5%82-dams-100692205/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
